Repository Room-Fit/frontend, pull requests merged in 2025-02, with the labels that each got.

#142 Feature#139: 프로필 상세조회 API 연동
  data/recentSurvey.json
  src/apps/config/site.ts
  src/entities/form/__tests__/FormFactory.test.tsx
  src/entities/form/config/formElementTypes.ts
  src/entities/form/contexts/FormStateContextProvider.tsx
  src/entities/form/ui/CheckBoxFormElement/CheckBoxFormElement.stories.tsx
  src/entities/form/ui/CheckBoxFormElement/CheckboxFormElement.tsx
  src/entities/form/ui/DoubleSliderFormElement/DoubleSliderFormElement.stories.tsx
  src/entities/form/ui/DoubleSliderFormElement/DoubleSliderFormElement.tsx
  src/entities/form/ui/DynamicForm/DynamicForm.stories.tsx
  src/entities/form/ui/DynamicForm/DynamicForm.tsx
  src/entities/form/ui/SelectorFormElement/SelectorFormElement.stories.tsx
  src/entities/form/ui/SelectorFormElement/SelectorFormElement.tsx
  src/entities/form/ui/SliderFormElement/SliderFormElement.stories.tsx
  src/entities/form/ui/SliderFormElement/SliderFormElement.tsx
  src/entities/form/ui/index.ts
  src/entities/profile/ui/CheckBoxDisplay/CheckBoxDisplay.stories.tsx
  src/entities/profile/ui/CheckBoxDisplay/CheckBoxDisplay.tsx
  src/entities/profile/ui/DoubleSliderDisplay/DoubleSliderDisplay.stories.tsx
  src/entities/profile/ui/DoubleSliderDisplay/DoubleSliderDisplay.tsx
  src/entities/profile/ui/DynamicReply/DynamicReply.stories.tsx
  src/entities/profile/ui/DynamicReply/DynamicReply.tsx
  src/entities/profile/ui/RangeDisplay/RangeDisplay.stories.tsx
  src/entities/profile/ui/RangeDisplay/RangeDisplay.tsx
  src/entities/profile/ui/SelectorDisplay/SelectorDisplay.stories.tsx
  src/entities/profile/ui/SelectorDisplay/SelectorDisplay.tsx
  src/entities/user/service/index.ts
  src/entities/user/service/keys.ts
  src/entities/user/service/readUserById.ts
  src/features/profile/service/index.ts
  src/features/profile/service/keys.ts
  src/features/profile/service/readSurveyReplyById.ts
  src/pages/profile/ProfileDetailPage.tsx
  src/pages/profile/ProfileEditPage.tsx
  src/shared/components/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
  src/shared/components/ToggleButtonGroup/ToggleButtonGroup.tsx
Labels: 리팩토링 요청, 기능 요청

#148 Feature#147 사용자 마이페이지 조회
  src/features/mypage/service/index.ts
  src/features/mypage/service/readMyInfo.ts
  src/pages/chat/ChatRoomPage.tsx
  src/pages/match/MatchDetailPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/profile/ProfileListPage.tsx
  src/shared/lib/decodeJWT.ts
Labels: 진행중, API 연동

#149 Fix#145 : 동일 activity 로 네비게이팅 되는 현상 해결
  package.json
  src/apps/layouts/NavBottom.tsx
  src/apps/stackflow.tsx
  src/shared/components/Link/Link.tsx
  yarn.lock
Labels: 버그 리포트, 우선순위 (상)

#151 Fix#150 : 프로필 찾기 페이지에서, 프로필을 등록하지 않은 사용자 선택시 빈 화면이 뜨는 현상 해결
  src/features/profile/service/readSurveyReplyById.ts
  src/pages/profile/ProfileDetailPage.tsx
  src/shared/lib/query.ts
Labels: 버그 리포트, 도메인 : profile

#154 Refactor#152 사용자 프로필 조회 변경 요청
  src/entities/profile/ui/ProfileModal/ProfileModal.tsx
  src/features/mypage/service/readMyInfo.ts
  src/features/profile/service/readSurveyReplyById.ts
  src/features/profile/service/readUserList.ts
  src/pages/mypage/MyPage.tsx
  src/pages/profile/ProfileDetailPage.tsx
  src/pages/profile/ProfileEditPage.tsx
  src/pages/profile/ProfileListPage.tsx
Labels: 리팩토링 요청

#155 Feature#153: 활성화된 NavBottom 강조 스타일 적용
  src/apps/layouts/NavBottom.tsx
Labels: 기능 요청, 디자인 변경

#157 Feature#156 채팅방 관련 기능(입장/퇴장/생성/조회)구현
  src/entities/chat/ui/ChatSideBar/ChatProfileSideBar.tsx
  src/features/chat/hooks/useChat.ts
  src/features/chat/service/exitChatRoom.ts
  src/features/chat/service/index.ts
  src/features/chat/ui/LeaveChatRoomButton.stories.tsx
  src/features/chat/ui/LeaveChatRoomButton.tsx
  src/features/match/service/joinChatRoom.ts
  src/features/match/ui/EnterChatRoomButton.stories.tsx
  src/features/match/ui/EnterChatRoomButton.tsx
  src/features/profile/service/createSurveyResponse.ts
  src/features/profile/service/readSurveyReplyById.ts
  src/pages/chat/ChatRoomListPage.tsx
  src/pages/chat/ChatRoomPage.tsx
  src/pages/match/MatchDetailPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/profile/ProfileEditPage.tsx
  src/pages/profile/ProfileListPage.tsx
Labels: 진행중, API 연동, 도메인 : chat

#158 Feature#156 채팅방 관련 기능(입장/퇴장/생성/조회)구현
  src/features/chat/hooks/useChat.ts
  src/features/chat/service/readUserChatRoom.ts
  src/features/match/service/joinChatRoom.ts
  src/pages/chat/ChatRoomListPage.tsx
  src/pages/chat/ChatRoomPage.tsx
  src/pages/match/MatchDetailPage.tsx
  src/pages/profile/ProfileDetailPage.tsx
Labels: 우선순위 (상), 진행중, API 연동, 도메인 : chat

#159 Fix#144: 프로필 등록 모달이 제대로 열리지 않는 현상 수정
  src/shared/components/Modal/Modal.tsx
  src/shared/hooks/useOnMountAnimation.ts
Labels: 버그 리포트, 우선순위 (상)

#161 Fix#160: 채팅 히스토리 무한 스크롤이 제대로 동작하지 않는 현상 해결
  src/entities/chat/ui/ChatInput/ChatInput.tsx
  src/features/chat/hooks/useChat.ts
  src/features/chat/hooks/useInfObserverFetch.ts
  src/features/chat/hooks/usePreviousMessageHistory.ts
  src/pages/chat/ChatRoomPage.tsx
  src/shared/components/Spinner/Spinner.tsx
Labels: 버그 리포트, 도메인 : chat
